language: node_js
node_js:
- '6'
cache:
  yarn: true
  directories:
    - node_modules
deploy:
  provider: npm
  email: guidokessels@gmail.com
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: true
    repo: guidokessels/xwing-data
